"""On-demand generator for an AST training config file.

``bioamla models ast train`` can read a TOML file (via ``--config``) whose
``[models]``, ``[training]``, and ``[augmentation]`` sections overlay the
command-line defaults. This module produces a documented starter for that file.

The template is a Python string (not a packaged data file) so it ships in the
wheel without extra packaging rules, and its keys/defaults are kept in step with
the ``ast train`` CLI options and the ``AugmentationConfig`` defaults.
"""

from __future__ import annotations

from pathlib import Path

from bioamla.exceptions import InvalidInputError

# Keep these values aligned with the `ast train` CLI option defaults and with
# bioamla.datasets.augmentation.AugmentationConfig. Comments document intent;
# every layer is OFF by default so a fresh file trains with no augmentation.
TRAIN_CONFIG_TEMPLATE = """\
# Bioamla AST training configuration
# Generated by: bioamla models ast init-config
#
# Pass this file to training with:
#   bioamla models ast train --train-dataset <data> --config ast_training.toml
#
# Only the three sections below are read. A command-line flag always overrides
# the value here, which in turn overrides the built-in default.

# =============================================================================
# MODEL
# =============================================================================
[models]
default_ast_model = "MIT/ast-finetuned-audioset-10-10-0.4593"  # base model to fine-tune

# =============================================================================
# TRAINING
# =============================================================================
[training]
learning_rate = 5.0e-5       # Initial learning rate
epochs = 1                   # Number of training epochs
batch_size = 8               # Per-device training batch size
eval_strategy = "epoch"      # "epoch", "steps", or "no"
save_strategy = "epoch"      # "epoch", "steps", or "no"
eval_steps = 1               # Steps between evals (only when eval_strategy = "steps")
save_steps = 1               # Steps between checkpoints (only when save_strategy = "steps")
logging_steps = 100          # Steps between log lines
report_to = "tensorboard"    # Metrics backend: "tensorboard", "mlflow", "none", ...

# =============================================================================
# AUGMENTATION
# On-the-fly audio augmentation during training. Every layer is OFF by default;
# turn on only the ones you need (here, or with the matching --<layer> CLI flag).
# Ranges/probabilities apply only to layers that are enabled.
# =============================================================================
[augmentation]
# --- Layers (each adds one audiomentations transform when true) ---
add_noise = false            # Add Gaussian noise (SNR range below)
time_stretch = false         # Stretch/compress time (rate range below)
pitch_shift = false          # Shift pitch (semitone range below)
gain = false                 # Random gain (dB range below)
gain_transition = false      # Smooth gain ramp (shares the gain dB range)
clipping_distortion = false  # Clipping distortion (percentile range below)

# --- Pipeline controls ---
probability = 0.8            # Chance the whole pipeline is applied to a sample (0-1)
multiplier = 1               # Repeat the train split N times with augmentation (1 = no copies)

# --- Per-layer ranges and probabilities (only used by enabled layers) ---
# Each *_probability is that layer's per-sample chance; it stacks with the
# pipeline-level `probability` above.
min_snr_db = 10.0            # Gaussian noise: min SNR (dB)
max_snr_db = 20.0            # Gaussian noise: max SNR (dB)
noise_probability = 0.5      # Gaussian noise: per-sample probability (0-1)
min_time_stretch = 0.8       # Time stretch: min rate
max_time_stretch = 1.2       # Time stretch: max rate
time_stretch_probability = 0.5  # Time stretch: per-sample probability (0-1)
min_pitch_shift = -4         # Pitch shift: min semitones
max_pitch_shift = 4          # Pitch shift: max semitones
pitch_shift_probability = 0.5   # Pitch shift: per-sample probability (0-1)
min_gain_db = -6.0           # Gain / gain transition: min (dB)
max_gain_db = 6.0            # Gain / gain transition: max (dB)
gain_probability = 0.5       # Gain: per-sample probability (0-1)
gain_transition_probability = 0.5  # Gain transition: per-sample probability (0-1)
clipping_probability = 0.5   # Clipping distortion: per-sample probability (0-1)
min_percentile_threshold = 0    # Clipping distortion: min percentile
max_percentile_threshold = 30   # Clipping distortion: max percentile
"""


def write_train_config(path: str | Path, force: bool = False) -> Path:
    """Write the AST training-config template to ``path``.

    Args:
        path: Destination file (parent directories are created).
        force: Overwrite an existing file instead of raising.

    Returns:
        The written path.

    Raises:
        InvalidInputError: If ``path`` exists and ``force`` is False.
    """
    out = Path(path)
    if out.exists() and not force:
        raise InvalidInputError(f"File already exists: {out}")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TRAIN_CONFIG_TEMPLATE)
    return out
